export type VocabWord = {
  french: string;
  arabic: string;
};

export type VocabList = {
  title: string;
  words: VocabWord[];
};

export type VocabUnit = {
  title: string;
  description: string;
  lists: VocabList[];
};

export const vocabularyData: VocabUnit[] = [
  // PARTIE I : Les Fondements (0% à 50% du Coran)
  {
    title: "Partie I : Les Fondements",
    description: "0% à 50% du Coran",
    lists: [
      {
        title: "Pronoms Démonstratifs",
        words: [
          { french: "Ceci (Masculin)", arabic: "هَٰذَا" },
          { french: "Cela / Celui-là (Masculin)", arabic: "ذَٰلِكَ" },
          { french: "Celle-ci (Féminin)", arabic: "هَٰذِهِ" },
          { french: "Celle-là (Féminin)", arabic: "تِلۡكَ" },
          { french: "Ceux-ci / Celles-ci (Pluriel)", arabic: "هٰٓؤُلَآءِ" },
          { french: "Ceux-là / Celles-là (Pluriel)", arabic: "أُوْلٰٓئِكَ" },
          { french: "Celui qui (Masculin)", arabic: "ٱلَّذِي" },
          { french: "Celle qui (Féminin)", arabic: "ٱلَّتِي" },
          { french: "Ceux qui (Pluriel masc.)", arabic: "ٱلَّذِينَ" },
        ],
      },
      {
        title: "Négations & Exceptions",
        words: [
          { french: "Oui", arabic: "نَعَمۡ" },
          { french: "Bien sûr / Si", arabic: "بَلَىٰ" },
          { french: "Absolument pas", arabic: "كَلَّا" },
          { french: "Sauf / Excepté", arabic: "إِلَّا" },
          { french: "Ne ... que / Rien d'autre que", arabic: "إِن ... إِلَّا" },
          { french: "Afin de ne pas", arabic: "أَلَّا" },
          { french: "Ne ... pas (Présent)", arabic: "لَا" },
          { french: "Ne ... pas (Passé / Général)", arabic: "مَا" },
          { french: "Ne ... jamais (Futur)", arabic: "لَنۡ" },
          { french: "N'a pas (Passé)", arabic: "لَمۡ" },
          { french: "N'est pas (Masc. 3ème pers.)", arabic: "لَيۡسَ" },
          { french: "Tu n'es pas (Masc. 2ème pers.)", arabic: "لَسۡتَ" },
          { french: "Autre que / Sans", arabic: "غَيۡر" },
          { french: "En dehors de / À l'exclusion de", arabic: "مِن دُونِ" },
        ],
      },
      {
        title: "Mots Interrogatifs",
        words: [
          { french: "Est-ce que", arabic: "هَلۡ" },
          { french: "Que / Quoi", arabic: "مَا" },
          { french: "Pourquoi", arabic: "لِمَ" },
          { french: "Qui", arabic: "مَنۡ" },
          { french: "Quand", arabic: "مَتَىٰ" },
          { french: "Où", arabic: "أَيۡنَ" },
          { french: "Comment", arabic: "كَيۡفَ" },
          { french: "Combien", arabic: "كَمۡ" },
          { french: "Quel / Lequel", arabic: "أَيُّ" },
          { french: "Comment / D'où", arabic: "أَنَّىٰ" },
        ],
      },
      {
        title: "Prépositions",
        words: [
          { french: "Au-dessus / Sur", arabic: "فَوۡقَ" },
          { french: "Sous / En dessous", arabic: "تَحۡتَ" },
          { french: "Droite", arabic: "يَمِين" },
          { french: "Gauche", arabic: "شِمَال" },
          { french: "Entre / Parmi", arabic: "بَيۡنَ" },
          { french: "Devant", arabic: "بَيۡنَ يَدَي" },
          { french: "Derrière / Successeur", arabic: "خَلۡفَ" },
          { french: "Derrière / Au-delà", arabic: "وَرَآءِ" },
          { french: "Autour de", arabic: "حَوۡلَ" },
          { french: "Où que / Partout où", arabic: "حَيۡثُ" },
        ],
      },
      {
        title: "Particules",
        words: [
          { french: "Dans / Par / Avec", arabic: "بـِ" },
          { french: "Loin de / À propos de", arabic: "عَنۡ" },
          { french: "Dans / Durant", arabic: "فِي" },
          { french: "Comme", arabic: "كَـ" },
          { french: "Pour / À", arabic: "لـ" },
          { french: "De / Depuis", arabic: "مِنۡ" },
          { french: "Vers", arabic: "إِلَىٰ" },
          { french: "Jusqu'à", arabic: "حَتَّىٰ" },
          { french: "Sur / Au-dessus", arabic: "عَلَىٰ" },
          { french: "Avec", arabic: "مَعَ" },
          { french: "Et / Par", arabic: "وَ" },
        ],
      },
      {
        title: "Connecteurs",
        words: [
          { french: "Certes / Vraiment", arabic: "إِنَّ" },
          { french: "Que", arabic: "أَنَّ" },
          { french: "Si", arabic: "إِنۡ" },
          { french: "Si (hypothèse)", arabic: "لَوۡ" },
          { french: "Comme si", arabic: "كَأَنَّ" },
          { french: "Mais", arabic: "لَٰكِن" },
          { french: "Quand / Lorsque", arabic: "إِذَا" },
          { french: "Si ce n'était", arabic: "لَوۡلَا" },
          { french: "Avant", arabic: "مِن قَبۡل" },
          { french: "Après", arabic: "مِن بَعۡد" },
          { french: "Puis / Ensuite", arabic: "ثُمَّ" },
        ],
      },
      {
        title: "Divers",
        words: [
          { french: "Doté de / Appartenant à", arabic: "ذُو" },
          { french: "Famille / Gens de", arabic: "أَهۡل" },
          { french: "Oh! / Ne vont-ils pas", arabic: "أَلَا" },
          { french: "Quel excellent", arabic: "نِعۡمَ" },
          { french: "Quel pire", arabic: "بِئۡسَ" },
          { french: "Pareil à / Comme", arabic: "مِثۡل" },
          { french: "Ou", arabic: "أَو" },
          { french: "Certains / Une partie", arabic: "بَعۡض" },
          { french: "Chaque / Tout", arabic: "كُلُّ" },
          { french: "Peut-être", arabic: "لَعَلَّ" },
          { french: "Ô!", arabic: "يَا" },
          { french: "Auprès de / Chez", arabic: "عِند" },
        ],
      },
    ],
  },
  // PARTIE II : Noms et Adjectifs (50% à 65% du Coran)
  {
    title: "Partie II : Noms et Adjectifs",
    description: "50% à 65% du Coran",
    lists: [
      {
        title: "Noms & Attributs d'Allah",
        words: [
          { french: "Seigneur", arabic: "رَبّ" },
          { french: "Le Tout Miséricordieux", arabic: "ٱلرَّحۡمَٰن" },
          { french: "Le Très Miséricordieux", arabic: "ٱلرَّحِيم" },
          { french: "Le Puissant", arabic: "عَزِيز" },
          { french: "Le Sage", arabic: "حَكِيم" },
          { french: "Le Grand Pardonneur", arabic: "غَفُور" },
          { french: "Le Clément", arabic: "حَلِيم" },
          { french: "L'Immense", arabic: "ٱلۡعَظِيم" },
          { french: "Le Très-Haut", arabic: "ٱلۡعَلِيّ" },
          { french: "L'Omniscient", arabic: "عَلِيم" },
          { french: "Le Parfaitement Connaisseur", arabic: "خَبِير" },
          { french: "L'Audiant", arabic: "سَمِيع" },
          { french: "Le Clairvoyant", arabic: "بَصِير" },
          { french: "Le Reconnaissant", arabic: "شَكُور" },
          { french: "L'Omnipotent", arabic: "قَدِير" },
          { french: "Le Garant", arabic: "وَكِيل" },
          { french: "Le Secoureur", arabic: "نَصِير" },
          { french: "Le Digne de louange", arabic: "حَمِيد" },
          { french: "L'Accueillant au repentir", arabic: "تَوَّاب" },
        ],
      },
      {
        title: "Attributs / Adjectifs",
        words: [
          { french: "Premier", arabic: "أَوَّل" },
          { french: "Dernier", arabic: "ءَاخِر" },
          { french: "Proche", arabic: "قَرِيب" },
          { french: "Loin", arabic: "بَعِيد" },
          { french: "Dur / Plus dur", arabic: "شَدِيد" },
          { french: "Grand / Plus grand", arabic: "كَبِير" },
          { french: "Beaucoup / La plupart", arabic: "كَثِير" },
          { french: "Rapide", arabic: "سَرِيع" },
          { french: "Peu / Petit", arabic: "قَلِيل" },
          { french: "Noble / Généreux", arabic: "كَرِيم" },
          { french: "Gardien", arabic: "حَفِيظ" },
          { french: "Meilleur", arabic: "أَحۡسَن" },
          { french: "Plus injuste", arabic: "أَظۡلَم" },
          { french: "Plus digne", arabic: "أَحَقّ" },
          { french: "Plus proche / Plus bas", arabic: "أَدۡنَىٰ" },
        ],
      },
      {
        title: "Prophètes & Messagers",
        words: [
          { french: "Messager", arabic: "رَسُول" },
          { french: "Prophète", arabic: "نَبِيّ" },
          { french: "Digne de confiance", arabic: "أَمِين" },
          { french: "Avertisseur", arabic: "نَذِير" },
          { french: "Moïse", arabic: "مُوسَىٰ" },
          { french: "Abraham", arabic: "إِبۡرَٰهِۧم" },
          { french: "Noé", arabic: "نُوح" },
          { french: "Joseph", arabic: "يُوسُف" },
          { french: "Jésus fils de Marie", arabic: "عِيسَى" },
          { french: "Adam", arabic: "ءَادَم" },
          { french: "Salomon", arabic: "سُلَيۡمَٰن" },
          { french: "David", arabic: "دَاوُۥد" },
          { french: "Aaron", arabic: "هَٰرُون" },
          { french: "Ismaël", arabic: "إِسۡمَٰعِيل" },
          { french: "Jonas", arabic: "يُونُس" },
        ],
      },
      {
        title: "Signes & Bénédictions",
        words: [
          { french: "Signe / Verset", arabic: "ءَايَة" },
          { french: "Le Coran", arabic: "ٱلۡقُرۡءَان" },
          { french: "L'Évangile", arabic: "ٱلۡإِنجِيل" },
          { french: "La Torah", arabic: "ٱلتَّوۡرَىٰة" },
          { french: "Bétail", arabic: "أَنۡعَام" },
          { french: "Montagne", arabic: "جَبَل" },
          { french: "Mer / Fleuve", arabic: "بَحۡر" },
          { french: "Rivière", arabic: "نَهَر" },
          { french: "Soleil", arabic: "شَمۡس" },
          { french: "Lune", arabic: "قَمَر" },
          { french: "Nuit", arabic: "لَيۡل" },
          { french: "Jour", arabic: "نَهَار" },
          { french: "Terre", arabic: "أَرۡض" },
          { french: "Cieux / Ciel", arabic: "سَمَآء" },
          { french: "Bienfait / Grâce", arabic: "نِعۡمَة" },
          { french: "Eau", arabic: "مَآء" },
        ],
      },
      {
        title: "Deen",
        words: [
          { french: "Religion", arabic: "دِين" },
          { french: "Affaire / Commandement", arabic: "أَمۡر" },
          { french: "Prière", arabic: "صَلَوٰة" },
          { french: "Aumône / Zakat", arabic: "زَكَوٰة" },
          { french: "Vérité", arabic: "حَقّ" },
          { french: "Faux", arabic: "بَٰطِل" },
          { french: "Louange", arabic: "حَمۡد" },
          { french: "Sagesse", arabic: "حِكۡمَة" },
          { french: "Piété", arabic: "تَقۡوَى" },
          { french: "Témoin / Martyr", arabic: "شَهِيد" },
          { french: "Évident / Clair", arabic: "مُبِين" },
          { french: "Lumière", arabic: "نُور" },
          { french: "Paix", arabic: "سَلَٰم" },
          { french: "Royauté / Domination", arabic: "مُلۡك" },
          { french: "Preuve / Autorité", arabic: "سُلۡطَٰن" },
        ],
      },
      {
        title: "Foi",
        words: [
          { french: "Dieu / Divinité", arabic: "إِلَٰه" },
          { french: "Un / Quelqu'un", arabic: "وَٰحِد" },
          { french: "Associé / Partenaire", arabic: "شَرِيك" },
          { french: "L'Invisible", arabic: "غَيۡب" },
          { french: "L'Apparent / Témoignage", arabic: "شَهَٰدَة" },
          { french: "Trône", arabic: "عَرۡش" },
          { french: "Livre / Écriture", arabic: "كِتَٰب" },
          { french: "Parole", arabic: "كَلِمَة" },
          { french: "Ange", arabic: "مَلَك" },
          { french: "Alliance / Pacte", arabic: "عَهۡد" },
          { french: "Permission", arabic: "إِذۡن" },
          { french: "Satan / Diables", arabic: "شَيۡطَٰن" },
        ],
      },
      {
        title: "Actes",
        words: [
          { french: "Actes / Actions", arabic: "عَمَل" },
          { french: "Bonne action / Bien", arabic: "حَسَنَة" },
          { french: "Mauvaise action / Péché", arabic: "سَيِّئَة" },
          { french: "Bien / Meilleur", arabic: "خَيۡر" },
          { french: "Mal / Pire", arabic: "شَرّ" },
          { french: "Péché", arabic: "إِثۡم" },
          { french: "Faute / Grief", arabic: "جُنَاح" },
          { french: "Illicite", arabic: "حَرَام" },
          { french: "Licite", arabic: "حَلَٰل" },
          { french: "Récit / Parole", arabic: "حَدِيث" },
          { french: "Bonne chose / Pur", arabic: "طَيِّب" },
          { french: "Récompense", arabic: "أَجۡر" },
        ],
      },
      {
        title: "Le Dernier Jour",
        words: [
          { french: "Jour", arabic: "يَوۡم" },
          { french: "Ce jour-là", arabic: "يَوۡمَئِذٍ" },
          { french: "Résurrection", arabic: "ٱلۡقِيَٰمَة" },
          { french: "Une Heure", arabic: "ٱلسَّاعَة" },
          { french: "Terme fixé", arabic: "أَجَل" },
          { french: "Compte", arabic: "حِسَاب" },
          { french: "L'Au-delà", arabic: "ٱلۡأٓخِرَة" },
          { french: "Pour toujours", arabic: "أَبَدًا" },
          { french: "Feu de l'Enfer", arabic: "نَار" },
          { french: "Géhenne", arabic: "جَهَنَّم" },
          { french: "Malheur à", arabic: "وَيۡل" },
          { french: "Châtiment / Punition", arabic: "عَذَاب" },
          { french: "Douloureux", arabic: "أَلِيم" },
          { french: "Récompense", arabic: "جَزَآء" },
          { french: "Paradis / Jardins", arabic: "جَنَّة" },
        ],
      },
      {
        title: "La Vie Présente",
        words: [
          { french: "Ce monde / La vie d'ici-bas", arabic: "ٱلدُّنۡيَا" },
          { french: "Les Mondes", arabic: "ٱلۡعَٰلَمِين" },
          { french: "Richesses / Biens", arabic: "أَمۡوَٰل" },
          { french: "Maison / Kaaba", arabic: "بَيۡت" },
          { french: "Demeure", arabic: "دَار" },
          { french: "Provision / Jouissance", arabic: "مَتَٰع" },
          { french: "Endroit / Lieu", arabic: "مَكَان" },
          { french: "Ville / Cité", arabic: "قَرۡيَة" },
          { french: "Chemin / Voie", arabic: "سَبِيل" },
          { french: "Mosquée", arabic: "مَسۡجِد" },
          { french: "Épreuve", arabic: "فِتۡنَة" },
          { french: "Rencontre", arabic: "لِقَآء" },
        ],
      },
      {
        title: "Proches",
        words: [
          { french: "Proches", arabic: "ذِي ٱلۡقُرۡبَىٰ" },
          { french: "Parents", arabic: "ٱلۡوَٰلِدَيۡنِ" },
          { french: "Mère", arabic: "أُمّ" },
          { french: "Père", arabic: "أَبّ" },
          { french: "Ancêtres", arabic: "ءَابَآء" },
          { french: "Conjoint / Époux", arabic: "زَوۡج" },
          { french: "Homme", arabic: "رَجُل" },
          { french: "Femme / Épouse", arabic: "ٱمۡرَأَة" },
          { french: "Descendance", arabic: "ذُرِّيَّة" },
          { french: "Fils / Enfants", arabic: "وَلَد" },
          { french: "Frères", arabic: "إِخۡوَٰن" },
          { french: "Tuteur / Allié", arabic: "وَلِيّ" },
          { french: "Mâle", arabic: "ذَكَر" },
          { french: "Femelle", arabic: "أُنثَىٰ" },
        ],
      },
      {
        title: "Divers (Noms)",
        words: [
          { french: "Visage", arabic: "وَجۡه" },
          { french: "Vue / Yeux", arabic: "أَبۡصَٰر" },
          { french: "Poitrine / Cœur", arabic: "صَدۡر" },
          { french: "Cœur", arabic: "قَلۡب" },
          { french: "Âme", arabic: "نَفۡس" },
          { french: "Force", arabic: "قُوَّة" },
          { french: "Gens / Peuple", arabic: "نَاس" },
          { french: "Nation / Communauté", arabic: "أُمَّة" },
          { french: "Être humain", arabic: "إِنسَٰن" },
          { french: "Serviteur", arabic: "عَبۡد" },
          { french: "Ennemi", arabic: "عَدُوّ" },
          { french: "Criminels", arabic: "مُجۡرِمِين" },
        ],
      },
      {
        title: "Pluriels Irréguliers",
        words: [
          { french: "Chrétiens", arabic: "نَصَٰرَىٰ" },
          { french: "Femmes", arabic: "نِسَآء" },
          { french: "Hommes", arabic: "رِجَال" },
          { french: "Os", arabic: "عِظَٰم" },
          { french: "Les morts", arabic: "مَوۡتَىٰ" },
          { french: "Mains", arabic: "أَيۡدِي" },
          { french: "Yeux", arabic: "أَعۡيُن" },
          { french: "Conjoints / Épouses", arabic: "أَزۡوَٰج" },
          { french: "Passions / Désirs", arabic: "أَهۡوَآء" },
          { french: "Intelligences / Esprits", arabic: "أَلۡبَٰب" },
          { french: "Portes", arabic: "أَبۡوَٰب" },
          { french: "Serments", arabic: "أَيۡمَٰن" },
        ],
      },
    ],
  },
  // PARTIE III : Les Formes Verbales (65% à 85% du Coran)
  {
    title: "Partie III : Les Formes Verbales",
    description: "65% à 85% du Coran",
    lists: [
      {
        title: "Forme II",
        words: [
          { french: "Changer", arabic: "بَدَّلَ" },
          { french: "Annoncer une bonne nouvelle", arabic: "بَشَّرَ" },
          { french: "Clarifier", arabic: "بَيَّنَ" },
          { french: "Embellir", arabic: "زَيَّنَ" },
          { french: "Glorifier", arabic: "سَبَّحَ" },
          { french: "Soumettre", arabic: "سَخَّرَ" },
          { french: "Confirmer", arabic: "صَدَّقَ" },
          { french: "Châtier", arabic: "عَذَّبَ" },
          { french: "Enseigner", arabic: "عَلَّمَ" },
          { french: "Avancer", arabic: "قَدَّمَ" },
          { french: "Traiter de menteur", arabic: "كَذَّبَ" },
          { french: "Informer", arabic: "نَبَّأَ" },
          { french: "Faire descendre", arabic: "نَزَّلَ" },
          { french: "Sauver", arabic: "نَجَّىٰ" },
          { french: "Se détourner", arabic: "وَلَّىٰ" },
        ],
      },
      {
        title: "Forme III",
        words: [
          { french: "Lutter", arabic: "جَٰهَدَ" },
          { french: "Combattre", arabic: "قَٰتَلَ" },
          { french: "Appeler", arabic: "نَادَىٰ" },
          { french: "Jouer l'hypocrite", arabic: "نَافَقَ" },
          { french: "Émigrer", arabic: "هَاجَرَ" },
        ],
      },
      {
        title: "Forme IV",
        words: [
          { french: "Voir", arabic: "أَبۡصَرَ" },
          { french: "Bien agir", arabic: "أَحۡسَنَ" },
          { french: "Faire sortir", arabic: "أَخۡرَجَ" },
          { french: "Faire entrer", arabic: "أَدۡخَلَ" },
          { french: "Envoyer", arabic: "أَرۡسَلَ" },
          { french: "Se soumettre", arabic: "أَسۡلَمَ" },
          { french: "Associer", arabic: "أَشۡرَكَ" },
          { french: "Réparer", arabic: "أَصۡلَحَ" },
          { french: "Se détourner", arabic: "أَعۡرَضَ" },
          { french: "Semer la corruption", arabic: "أَفۡسَدَ" },
          { french: "Réussir", arabic: "أَفۡلَحَ" },
          { french: "Avertir", arabic: "أَنذَرَ" },
          { french: "Faire descendre", arabic: "أَنزَلَ" },
          { french: "Dépenser", arabic: "أَنفَقَ" },
          { french: "Détruire", arabic: "أَهۡلَكَ" },
          { french: "Révéler", arabic: "أَوۡحَىٰ" },
          { french: "Donner la vie", arabic: "أَحۡيَا" },
        ],
      },
      {
        title: "Forme V",
        words: [
          { french: "Méditer", arabic: "تَفَكَّرَ" },
          { french: "Se rappeler", arabic: "تَذَكَّرَ" },
          { french: "Placer sa confiance", arabic: "تَوَكَّلَ" },
          { french: "Devenir clair", arabic: "تَبَيَّنَ" },
          { french: "Patienter", arabic: "تَرَبَّصَ" },
          { french: "Se détourner", arabic: "تَوَلَّىٰ" },
          { french: "Reprendre l'âme", arabic: "تَوَفَّىٰ" },
        ],
      },
      {
        title: "Formes VI & VII",
        words: [
          { french: "Être béni", arabic: "تَبَارَكَ" },
          { french: "S'interroger", arabic: "تَسَآءَلَ" },
          { french: "Retourner", arabic: "ٱنقَلَبَ" },
          { french: "Cesser", arabic: "ٱنتَهَى" },
        ],
      },
      {
        title: "Forme VIII",
        words: [
          { french: "Diverger", arabic: "ٱخۡتَلَفَ" },
          { french: "Suivre", arabic: "ٱتَّبَعَ" },
          { french: "Prendre", arabic: "ٱتَّخَذَ" },
          { french: "Craindre Allah", arabic: "ٱتَّقَى" },
          { french: "Être guidé", arabic: "ٱهۡتَدَى" },
          { french: "Chercher", arabic: "ٱبۡتَغَى" },
        ],
      },
      {
        title: "Formes IX & X",
        words: [
          { french: "Noircir", arabic: "ٱسۡوَدَّ" },
          { french: "Blanchir", arabic: "ٱبۡيَضَّ" },
          { french: "Verdir", arabic: "ٱخۡضَرَّ" },
          { french: "Se hâter", arabic: "ٱسۡتَعۡجَلَ" },
          { french: "Demander pardon", arabic: "ٱسۡتَغۡفَرَ" },
          { french: "S'enorgueillir", arabic: "ٱسۡتَكۡبَرَ" },
          { french: "Se moquer", arabic: "ٱسۡتَهۡزَأَ" },
          { french: "Répondre", arabic: "ٱسۡتَجَابَ" },
          { french: "Pouvoir", arabic: "ٱسۡتَطَاعَ" },
          { french: "Être droit", arabic: "ٱسۡتَقَامَ" },
        ],
      },
      {
        title: "Forme I - Partie 1",
        words: [
          { french: "Ouvrir / Juger", arabic: "فَتَحَ" },
          { french: "Envoyer / Ressusciter", arabic: "بَعَثَ" },
          { french: "Faire", arabic: "جَعَلَ" },
          { french: "Rassembler", arabic: "جَمَعَ" },
          { french: "Élever", arabic: "رَفَعَ" },
          { french: "Maudire", arabic: "لَعَنَ" },
          { french: "Secourir", arabic: "نَصَرَ" },
          { french: "Créer", arabic: "خَلَقَ" },
          { french: "Tuer", arabic: "قَتَلَ" },
          { french: "Sortir", arabic: "خَرَجَ" },
          { french: "Entrer", arabic: "دَخَلَ" },
          { french: "Se prosterner", arabic: "سَجَدَ" },
          { french: "Se souvenir", arabic: "ذَكَرَ" },
          { french: "Pourvoir", arabic: "رَزَقَ" },
          { french: "Mécroire", arabic: "كَفَرَ" },
        ],
      },
      {
        title: "Forme I - Partie 2",
        words: [
          { french: "Adorer", arabic: "عَبَدَ" },
          { french: "Prescrire / Écrire", arabic: "كَتَبَ" },
          { french: "Regarder", arabic: "نَظَرَ" },
          { french: "Frapper / Proposer", arabic: "ضَرَبَ" },
          { french: "Endurer", arabic: "صَبَرَ" },
          { french: "Comprendre", arabic: "عَقَلَ" },
          { french: "Être injuste", arabic: "ظَلَمَ" },
          { french: "Posséder", arabic: "مَلَكَ" },
          { french: "Pardonner", arabic: "غَفَرَ" },
          { french: "Entendre", arabic: "سَمِعَ" },
          { french: "Savoir", arabic: "عَلِمَ" },
          { french: "Travailler / Agir", arabic: "عَمِلَ" },
          { french: "Faire miséricorde", arabic: "رَحِمَ" },
          { french: "Témoigner", arabic: "شَهِدَ" },
          { french: "Protéger", arabic: "حَفِظَ" },
        ],
      },
      {
        title: "Verbes Irréguliers - Partie 1",
        words: [
          { french: "Retourner", arabic: "رَدَّ" },
          { french: "S'égarer", arabic: "ضَلَّ" },
          { french: "Penser / Croire", arabic: "ظَنَّ" },
          { french: "Toucher", arabic: "مَسَّ" },
          { french: "Demander", arabic: "سَأَلَ" },
          { french: "Prendre", arabic: "أَخَذَ" },
          { french: "Manger", arabic: "أَكَلَ" },
          { french: "Ordonner", arabic: "أَمَرَ" },
          { french: "Voir", arabic: "رَأَى" },
          { french: "Vouloir", arabic: "شَآءَ" },
          { french: "Venir", arabic: "جَآءَ" },
          { french: "Dire", arabic: "قَالَ" },
          { french: "Être", arabic: "كَانَ" },
        ],
      },
      {
        title: "Verbes Irréguliers - Partie 2",
        words: [
          { french: "Trouver", arabic: "وَجَدَ" },
          { french: "Promettre", arabic: "وَعَدَ" },
          { french: "Protéger", arabic: "وَقَىٰ" },
          { french: "Se repentir", arabic: "تَابَ" },
          { french: "Mourir", arabic: "مَاتَ" },
          { french: "Craindre", arabic: "خَافَ" },
          { french: "Appeler / Invoquer", arabic: "دَعَا" },
          { french: "Pardonner", arabic: "عَفَا" },
          { french: "Décréter", arabic: "قَضَىٰ" },
          { french: "Suffire", arabic: "كَفَىٰ" },
          { french: "Guider", arabic: "هَدَى" },
          { french: "Être satisfait", arabic: "رَضِىَ" },
          { french: "Oublier", arabic: "نَسِىَ" },
        ],
      },
    ],
  },
];
